comments/urls.py
from django.conf.urls import url
from django.contrib import admin
from comments import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<topic_id>[0-9]+)/$', views.post_comment, name='post_comment'),
]

forum/urls.py
from django.conf.urls import url
from forum import views, search_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^search/', search_views.MySeachView(), name='haystack_search'),
    url(r'^topic/(?P<topic_id>\d+)/$', views.TopicDetailView.as_view(), name='detail'),
    url(r'^category/(?P<categories_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^topic_create/$', views.TopicCreateView.as_view(), name='create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fouram/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('forum.urls', namespace='forum')),
    url(r'', include('user.urls', namespace='user')),
    url(r'', include('comments.urls')),
    url(r'', include('ckeditor_uploader.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'', include('django.contrib.auth.urls', namespace='auth')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.conf.urls import url

from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^user_info/(?P<user_id>\d+)/$', views.UserInfoView.as_view(), name='info'),
    url(r'^updateinfo', views.updateInfo, name='updateinfo'),
    url(r'^create', views.signaturechange, name='create'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% block title %}{% endblock %}
{#    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}">#}
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'forum/forum.css' %}">
    {% block css %}{% endblock %}
</head>
<body>

<div id="header">
    <div class="banner">
        <a href="../../../">
            <font size="7" color="white">
                <b>４am</b>
            </font>
        </a>
    </div>

<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
     <div class="navbar-header">
         <ul class="nav navbar-nav">
             <li>
                 <a href="{% url 'forum:index' %}" class="navbar-brand">首页</a>
             </li>
             <li>
                <form class="navbar-form navbar-right" method="get" action="{% url 'haystack_search' %}">
                    <div class="form-group">
                        <input name="q" class="form-control" placeholder="搜索帖子">
                    </div>
                    <button type="submit" class="btn btn-primary">确定</button>
                </form>
            </li>
         </ul>
     </div>
     <div id="navbar" class="collapse navbar-collapse bs-navbar-collapse">
         {% if user.is_authenticated %}
         <ul class="nav navbar-nav" style="margin-left: 680px;">
             <li>
                 <a href="{% url 'user:info' request.user.id %}">{{ user.username }}</a>
             </li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'auth:logout' %}?next={{ request.path }}" >退出</a>
            </li>
         </ul>
         {% else %}
         <ul class="nav navbar-nav" style="margin-left: 980px">
             <li>
                 <a href="{% url 'auth:login' %}?next={{ request.path }}">登录</a>
             </li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'user:register' %}?next={{ request.path }}">注册</a>
            </li>
         </ul>
         {% endif %}
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}


<footer>
  <div class="modal-footer" id="footer-back">
      <div class="row">
          <div class="footer-link">
          <p style="margin-right: 550px">
              <a href="{% url 'forum:index' %}">首页</a>
              <a href="https://www.zhihu.com/people/guo-wei-liang-48/">知乎</a>
              <a href="https://github.com/Kwokwai">Github</a>
          </p>
        <div class="copyright" style="margin-right: 520px">Copyright @2017 By Kwok</div>
      </div>
      </div>
  </div>
</footer>

</body>
</html>

templates/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>

<div class="container " style="min-height: 500px">
    <div class="row">
        <div class="col-md-9 at-edit">
            <form action="" method="post">{% csrf_token %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        发布新帖子
                    </div>
                    <div class="panel-body">
                        {{ form.title }}
                    </div>
                    <div class="panel-body" >
                        {{ form.content|safe }}
                    </div>
                    <div class="panel-body">
                        {{ form.categories }}
                    </div>
                </div>
            <button type="submit"  class="btn btn-primary">发布</button>
            </form>
        </div>
    </div>
</div>
</body>
{% endblock %}

templates/detail.html
{% extends "base.html" %}
{% load paginator_tags %}
{% load staticfiles %}
{% load myfilters %}
{% block content %}

<div id="main">
    <ol class="breadcrumb">
    <li>
        <a href="{% url 'forum:index' %}">4am</a>    </li>
    <li>
        <a href="{% url 'forum:category' topic.categories_id %}">{{ topic.categories }}</a>
    </li>
</ol>
    <div class="t" style="margin-bottom: 0;border-bottom: 0">
        <table cellspacing="0" cellpadding="0" width="100%" align="center">
             <tbody>
              <tr>
               <td class="h"> --&gt; <b>本頁主題:</b>{{ topic.title }}
                    {% if user.is_authenticated %}
                    <a class="fr a2 fn" href="{% url 'forum:create' %}">发布新主题</a>
                    {% else %}
                        <span class="pull-right">需要登录才能发新帖子</span>
                    {% endif %}
               </td>
               <td class="h" style="text-align:right;"></td>

              </tr>
             </tbody>
        </table>
    </div>
    <div class="t t2" style="border-top: 0">
        <table cellspacing="0" cellpadding="0" width="100%" align="center">
            <tbody>
                <tr class="tr1 do_not_catch">
                    <!--作者区域--->
                    <td width="20%" rowspan="2" class="r_two">
                        <div class="panel" style="margin-left: 10px">
                            <div class="panel-heading panel-default">
                               <a href="{{ topic.author.get_absolute_url }}" style="font-size: 25px">{{ topic.author }}</a>
                            </div>
                            <div class="panel-body">
                                <img src="{{ topic.author.avatar.url }}" style="width: 120px;margin-left: 50px">
                            </div>
                            <div class="panel-body">
                                {{ topic.author.signature }}
                            </div>
                        </div>
                    </td>
                    <!--正文区域-->
                    <td height="100%" valign="top" style="padding: 5px 15px 0 15px;border: 0;width: 80%;overflow: hidden">
                        <div class="panel">
                            <div class="panel-heading panel-default" style="font-size: 20px">
                                <strong>{{ topic.title }}</strong>
                                <time class="submit-date pull-right" style="margin-left: 10px">{{ topic.create_date }}&nbsp;&nbsp;&nbsp;</time>
                            </div>
                            <div class="panel-body" style="min-height: 210px">
                                <h3>{{ topic.content|custom_markdown }}</h3>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!--评论区域-->
    <div class="t t2">
        <table cellspacing="0" cellpadding="0" width="100%" align="center">
            {% for comment in comment_list %}
            <tr class="tr3 tr1">
                <th width="10%"  class="r_two">
                    <img src="{{ comment.name.avatar.url }}" style="width: 96px; height: 96px;">
                </th>
                <th>
                    <div class="panel" style="min-height: 150px">
                         <div class="panel-heading panel-default">
                            <a href="{{ comment.name.get_absolute_url }}">{{ comment.name }}</a>
                             <span class="pull-right">{{ forloop.counter }} 楼</span>
                             <time class="submit-date pull-right" style="margin-left: 10px">{{ comment.created_time }}&nbsp;&nbsp;&nbsp;</time>
                        </div>
                        <div class="panel-body">{{ comment.text|custom_markdown }}</div>
                    </div>
                    {{ comment.name.signature }}
                </th>
            </tr>
            {% empty %}
            <tr>暂无评论</tr>
            {% endfor %}
        </table>
    {% paginator %}
    </div>
<!--回复区域-->
<form action="{% url 'comments:post_comment' topic_id=topic.id %}" method="post" class="comment-form">    {% csrf_token %}
    {% if user.is_authenticated %}
        {% if user.is_active %}
    <div class="t">
        <table cellpadding="0" cellspacing="0" align="center" width="90%">
            <tr>
                <td class="h" colspan="2"><b>回帖</b></td>
            </tr>
            <tr></tr>
            <tr>
                <td width="20%" bgcolor="#F9F9EC" style="padding: 7px">

                </td>

                <td width="80%" bgcolor="#F9F9EC" style="padding: 7px">
                    <div class="control-group">
                        <div class="controls" style="width: 500px">
                            <label for="{{ form.text.id_for_label }}" >评论：</label>
                            {{ form.text }}
                        </div>
                    </div>
                    <div class="controls">
                        <button type="submit" class="btn btn-primary" style="margin-left: 450px">发表</button>
                    </div>
                </td>
            </tr>
        </table>
    </div>
        {% endif %}
    {% else %}
    <div class="t">
        <table cellpadding="0" cellspacing="0" align="center" width="90%">
            <tr>
                <td class="h" colspan="2"><b>回帖</b>
                    您尚未登录，请先登录才能评论。
            </td>
            </tr>
        </table>
    </div>
    {% endif %}
</form>



{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load paginator_tags %}
{% block title %}
<title>4am</title>
{% endblock %}

{% block css %}
{% load static %}

{% endblock %}
{% block content %}

<!--板块分类-->
<ol class="breadcrumb">
    <li>
        <a href="{% url 'forum:index' %}">首页</a>
    </li>
    {% for category in category_list %}
    <li>
        <a href="{% url 'forum:category' category.id %}">{{ category.category_name }}</a>
    </li>
    {% endfor %}
</ol>

<!--主题板快-->
<div id="main" style="min-height: 400px">
    <div class="t" style="margin: 3px auto">
        <table cellspacing="0" cellpadding="0" width="100%" id="ajaxtable">
            <tbody>
                <tr>
                    <th class="h" colspan="5" style="width: 100%">
                        <a href="#">主板块</a>
                        {% if user.is_authenticated %}
                        <a class="fr a2 fn" href="{% url 'forum:create' %}">发布新主题</a>
                        {% else %}
                            <span class="pull-right">需要登录才能发新帖子</span>
                        {% endif %}
                    </th>
                </tr>
            </tbody>
            <tbody style="table-layout: fixed">
                <tr class="tr2 tac">
                    <td>作者</td>
                    <td width="70%">主题</td>
                    <td width="８%">发帖时间</td>
                    <td>点击量</td>
                    <td>板块</td>
                </tr>
                {% for topic in topic_list %}
                <tr class="tr3 t_one tac {{ topic.id }}">
                    <td>
                      <a href="{{ topic.author.get_absolute_url }}">{{ topic.author }}</a>
                    </td>
                    <td class="tal" style="padding-left: 8px">
                        <a href="{% url 'forum:detail' topic.id %}">{{ topic.title }}</a>
                    </td>
                    <td >
                        <h5>{{ topic.create_date }}</h5>
                    </td>
                    <td>
                        <h4>{{ topic.views }}</h4>
                    </td>
                    <td>
                        <h5>{{ topic.categories }}</h5>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <div class="" style="margin-left: 550px">
            {% paginator %}
    </div>
    </div>
</div>

{% endblock %}

templates/user_info.html
{% extends 'base.html' %}
{% load myfilters %}
{% block content %}

<div id="showmenu" style="z-index:100;display:none;"></div>
<div id="blank" style="height:10px; clear:both"></div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <!--头像区域-->
            <div class="well" style="background: white">
                <div class="panel-heading panel-default">
                       <a href="{{ topic.author.get_absolute_url }}" style="font-size: 25px">{{ info.user }}</a>
                    </div>
                <div class="panel">
                    <div class="panel-body">
                        <img src="{{ info.avatar.url }}" style="width: 230px;margin-left: 28px">
                    </div>
                </div>
                {% if user == info.user %}
                    {% if user.is_active %}
                <form action="{% url 'user:updateinfo' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <span>修改头像</span>
                            </div>
                            <div class="panel-body">
                                <input name="avatar" type="file"  >
                            </div>
                            <div class="panel-footer">
                                <button id="avatar" class="btn btn-primary" type="submit" >确认</button>
                            </div>
                        </div>
                    </form>
                        {% endif %}
                {% else %}

                {% endif %}
            </div>
            <!--签名区域-->
             <div class="well" style="background: white">
                 {{ info.signature }}
                 {% if user == info.user %}
                 <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">修改签名</button>
                 {% else %}

                {% endif %}
             </div>
        </div>
        <!--评论板块-->
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                        共{{ comment_nums }}条评论
                    </div>
                    {% for comment in comment_list %}

                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="{% url 'forum:detail' comment.post_id %}">{{ comment.text|safe|truncatechars:36 }}</a>
                            <br>
                            来自--
                            <a href="{% url 'forum:detail' comment.post_id %}" >{{ comment.post.title|safe|truncatechars:15 }}</a>
                            <time class="submit-date pull-right" style="margin-left: 10px" >{{ comment.created_time }}</time>
                        </li>
                    </ul>
                    {% empty %}
                    <div class="panel-body">
                         暂时无评论
                    </div>
                {% endfor %}
            </div>
            <!--帖子板块-->
            <div class="panel panel-default">
                <div class="panel-heading">
                    共{{ topic_nums }}个帖子
                </div>
                {% for topic in topic_list%}
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="{% url 'forum:detail' topic.id %}">{{ topic.title }}</a>
                            <time class="submit-date pull-right" style="margin-left: 10px" >{{ topic.create_date }}</time>
                        </li>
                    </ul>
                    {% empty %}
                    <div class="panel-body">
                         暂时没发帖子
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
	<div class="modal-dialog">
		<div class="modal-content">
            <form action="{% url 'user:create' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <textarea  name="signature" class="form-control"  required="required" title="" id="textarea" placeholder="{{ info.signature }}"></textarea><br>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                    </button>
                    <button type="submit" class="btn btn-primary" value="Submit">确定</button>
                </div>
            </form>
		</div>
	</div>
</div>

{% endblock %}